site_name: 'Documentation'

nav:
  - Home: index.md
  - Source Component: source-component.md
  - Pipelines: pipelines.md
  - GitOps Application: gitops-application.md
  - OpenShift AI: rhoai.md

plugins:
  - techdocs-core